# Thank you to https://github.com/marketplace/actions/prettier-action

name: Linter

on:
  pull_request:
  push:
    branches:
      - '*'

permissions:
  contents: write

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Debugging Step 1
        run: echo "Current Directory; $PWD"

      - name: Debugging Step 2
        run: git remote -v

      - name: Debugging Step 3
        run: git status
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{github.event.pull_request.head.ref }}

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write **/*.md
