# Thank you to https://github.com/marketplace/actions/prettier-action

name: Linter

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write **/*.md
